export const UPDATE_MESSAGE = "UPDATE_MESSAGE";
export const LOAD_MESSAGES = "LOAD_MESSAGES";
export const UPDATE_TYPING = "UPDATE_TYPING";

export const UPDATE_LOGIN_STATUS = "UPDATE_LOGIN_STATUS";

export const GET_APP_DETAILS_LOADING = "GET_APP_DETAILS_LOADING";
export const GET_APP_DETAILS_SUCCESS = "GET_APP_DETAILS_SUCCESS";
export const GET_APP_DETAILS_ERROR = "GET_APP_DETAILS_ERROR";
